### PR TITLE
Added title and description text

### PR DESCRIPTION
**Pull request by wuletawwonte**
Changes made 
- Added about section title
- Added description of the about section

### CODE REVIEW

**Review by Donard97 — CHANGES_REQUESTED** [review]
## Hello @wuletawwonte , ✋  

_You did a tremendous job on this project. I am amazed by your work. Good job! 💯💯💯_ 

There are some issues that you still need to work on to go to the next project! You have only a few more steps and you are done! 💪 💪 💪 

giphy


## Required Changes ♻️

- [x] Kindly change the main header  `<h2>Wuletaw Wonte</h2>` to h1 tag
- [x] Please add linters files: .stylelintrc and .hintrc following linter configuration [link](https://github.com/microverseinc/linters-config/tree/master/html-css)
- [x] Kindly add a .gitignore file and ignore node_modules because they can be installed when you will install linters and you have to ignore them before pushing into Github

## Optional suggestions

**[Suggestion] Please next review do not merge anything without getting feedback first from reviewers. In this case, we have to make the project invalid but you had most of the code on this branch so I continued with the review. 👍** 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by wuletawwonte** [comment]
### Hi @Donard97 

Thanks for the great review. I tried to fix all the issues you mentioned. Can I continue merging the branch with the base branch. 

One other thing, Shall I wait for a review every time I need to merge to the base branch. Because I have limited reviews I thought I should request it only if it is very necessary.

**Comment by Donard97** [comment]
> ### Hi @Donard97
> Thanks for the great review. I tried to fix all the issues you mentioned. Can I continue merging the branch with the base branch.
> 
> One other thing, Shall I wait for a review every time I need to merge to the base branch. Because I have limited reviews I thought I should request it only if it is very necessary.

Hi @wuletawwonte , good job on implementing the required changes. Please do not merge branches without first getting approved for this milestone. Submit your project and wait for the feedback. Keep coding! 💪

**Review by Lordkaito — APPROVED** [review]
Hi @wuletawwonte,

# STATUS: APPROVED ✅ ✅ 



Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
